import { vi } from 'vitest';
import { randomUUID } from 'crypto';

let inMemoryNodes: Map<string, any>; // Shared state for the mock
let inMemoryRelationships: Map<string, any>;

export const resetNeo4jMockState = () => {
  inMemoryNodes = new Map<string, any>();
  inMemoryRelationships = new Map<string, any>();
  console.log('--- Neo4j Mock State Reset ---'); // Keep commented for now
};

resetNeo4jMockState(); // Initial reset when the mock module is first loaded

const mockDriverInstance = {
  session: vi.fn().mockImplementation(() => {
    const mockSession = {
      run: vi.fn().mockImplementation((query, params) => {
        const normalizedQuery = query.replace(/\s+/g, ' ').trim();
        console.log('Mock Session Run:', { query: normalizedQuery, params, inMemoryNodesSize: inMemoryNodes.size });

        // Simulate OPTIONAL MATCH existence check query
        if (normalizedQuery.includes('OPTIONAL MATCH (a {id: $from})') && normalizedQuery.includes('RETURN a IS NOT NULL AS fromExists, b IS NOT NULL AS toExists')) {
          const fromExists = inMemoryNodes.has(params.from);
          const toExists = inMemoryNodes.has(params.to);

          const mockRecord = {
            keys: ['fromExists', 'toExists'],
            length: 2,
            _fields: [fromExists, toExists],
            get: vi.fn().mockImplementation((key) => {
              if (key === 'fromExists') return fromExists;
              if (key === 'toExists') return toExists;
              return undefined;
            }),
            toObject: vi.fn().mockImplementation(() => ({ fromExists, toExists }))
          };
          return Promise.resolve({ records: [mockRecord] });
        }

        // Simulate Node Creation Query: CREATE (n:Label $props) RETURN n.id AS id
        if (normalizedQuery.includes('CREATE (n') && normalizedQuery.includes('$props)')) {
          const nodeId = params.props.id; // Access id from props
          inMemoryNodes.set(nodeId, params.props);
          return Promise.resolve({ records: [{ get: (key) => (key === 'id' ? nodeId : undefined) }] });
        }

        // Simulate Relationship Creation Query: MATCH (a {id: $fromId}), (b {id: $toId}) CREATE (a)-[r:$type]->(b) SET r = $props, r.edgeId = $edgeId RETURN r
        if (normalizedQuery.includes('CREATE (a)-[r') && normalizedQuery.includes('SET r = $props, r.edgeId = $edgeId') && normalizedQuery.includes('RETURN r')) {
          const relId = params.edgeId; // Use edgeId from params as it's generated by the adapter
          const fromNodeId = params.from;
          const toNodeId = params.to;
          
          // Extract type from query string
          const typeMatch = normalizedQuery.match(/CREATE \(a\)-\[r:([A-Z0-9_]+)\]->\(b\)/);
          const relType = typeMatch ? typeMatch[1] : 'UNKNOWN';
          
          const properties = params.props;
          inMemoryRelationships.set(relId, { id: relId, from: fromNodeId, to: toNodeId, type: relType, properties });
          // Simulate Neo4j record structure for RETURN r
          return Promise.resolve({ records: [{ get: (key) => (key === 'r' ? { elementId: relId, properties: properties, type: relType } : undefined) }] });
        }

        // Simulate Node Existence Check Query: MATCH (n {id: $id}) RETURN n
        if (normalizedQuery.includes('MATCH (n {id: $id}) RETURN n')) {
          const nodeId = params.id;
          if (inMemoryNodes.has(nodeId)) {
            const nodeProps = inMemoryNodes.get(nodeId);
            return Promise.resolve({
              records: [{ get: (key) => (key === 'n' ? { properties: nodeProps } : undefined) }]
            });
          }
          return Promise.resolve({ records: [] });
        }

        // Simulate Relationship Retrieval Query: MATCH (n)-[r]-(m) WHERE id(n) = $id ... RETURN r, type(r) AS relType, id(r) AS relId, startNode(r) AS startNode, endNode(r) AS endNode
        if (normalizedQuery.includes('RETURN r, type(r) AS relType')) {
          const searchNodeId = params.nodeId || params.id;
          
          // Determine direction from query structure
          let direction = 'both';
          if (normalizedQuery.includes('-[r:') && normalizedQuery.includes(']->')) direction = 'outgoing';
          else if (normalizedQuery.includes('-[r]->')) direction = 'outgoing';
          else if (normalizedQuery.includes('<-[r:') && normalizedQuery.includes(']-')) direction = 'incoming';
          else if (normalizedQuery.includes('<-[r]-')) direction = 'incoming';
          
          // Determine type filter from query
          let typeFilter = null;
          const typeMatch = normalizedQuery.match(/\[r:([A-Z0-9_]+)\]/);
          if (typeMatch) {
            typeFilter = typeMatch[1];
          }
          
          const results = Array.from(inMemoryRelationships.values()).filter(rel => {
            if (typeFilter && rel.type !== typeFilter) return false;
            if (direction === 'outgoing') return rel.from === searchNodeId;
            if (direction === 'incoming') return rel.to === searchNodeId;
            return rel.from === searchNodeId || rel.to === searchNodeId;
          }).map(rel => ({
            get: (key) => {
              if (key === 'r') return { elementId: rel.id, properties: rel.properties };
              if (key === 'relType') return rel.type;
              if (key === 'relId') return rel.id;
              if (key === 'fromId' || key === 'startNode') return rel.from; // getNodeRelationships returns fromId/toId directly
              if (key === 'toId' || key === 'endNode') return rel.to;
              return undefined;
            },
            _fields: [
              { elementId: rel.id, properties: rel.properties },
              rel.type,
              rel.id,
              rel.from,
              rel.to
            ]
          }));
          return Promise.resolve({ records: results });
        }
        
        // Simulate DELETE queries for nodes (e.g., from GraphStoreAdapter.deleteNode)
        if (normalizedQuery.includes('DETACH DELETE')) {
            const nodeIdToDelete = params.id;
            const nodesBefore = inMemoryNodes.size;
            inMemoryNodes.delete(nodeIdToDelete);
            // Also delete relationships connected to this node
            inMemoryRelationships.forEach((rel, key) => {
                if (rel.from === nodeIdToDelete || rel.to === nodeIdToDelete) {
                    inMemoryRelationships.delete(key);
                }
            });
            return Promise.resolve({ records: [{ get: () => (nodesBefore - inMemoryNodes.size > 0 ? 1 : 0) }] });
        }

        console.warn('Unhandled Cypher query in mockSession.run:', normalizedQuery, params);
        return Promise.resolve({ records: [] });
      }),
      close: vi.fn().mockResolvedValue(undefined),
      executeWrite: vi.fn().mockImplementation(async (cb) => {
        const txc = mockSession; // Pass mockSession as the TransactionContext
        const result = await cb(txc);
        return result;
      }),
      executeRead: vi.fn().mockImplementation(async (cb) => {
        const txc = mockSession; // Pass mockSession as the TransactionContext
        const result = await cb(txc);
        return result;
      }),
    };
    return mockSession;
  }),
  close: vi.fn().mockResolvedValue(undefined),
  verifyConnectivity: vi.fn().mockResolvedValue(undefined),
};

export default {
  driver: vi.fn().mockReturnValue(mockDriverInstance),
  auth: { basic: vi.fn() },
};
